services:
  app:
    build: .
    container_name: web_socket_app
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=messages_db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  app-network:
    driver: bridge
